
build:
	docker build -t yocto-builder .

run:
	docker run -i --entrypoint=/home/peernohell/projects/yocto-builder/build.sh -v /home/peernohell/projects/yocto-builder:/home/peernohell/projects/yocto-builder -w /home/peernohell/projects/yocto-builder yocto-builder
